### PR TITLE
fix bug of data model contains spaces

### PR DESCRIPTION
**Pull request by SimonDolph**

### CODE REVIEW

**Comment by ijse** [comment]
Thanks for your pr.
But it fail on Windows due to the quote problem.

**Comment by SimonDolph** [comment]
Sorry for that, I'm using Mac, and I don't test it on Windows. But if no quotes, it fails on my Mac.

**Comment by ijse** [comment]
I know that. This is okay for Linux and Mac but Windows.
I have another plan and am working on it.

**Comment by ijse** [comment]
@SimonDolph  checkout _planB_.
https://github.com/ijse/freemarker.js/tree/planB

**Comment by SimonDolph** [comment]
It works after I change 1 line in index.js
from

```
var args = [tplFile, '-C', cfgFile, '-o=' + tmpFile];
```

to

```
var args = [tplFile, '-C', cfgFile, '-o', tmpFile];
```

Am I on the right way?

**Comment by ijse** [comment]
@SimonDolph  Try 35f34d669a31846596fc65eafbae828fd1d7c963

**Comment by SimonDolph** [comment]
It works, nice job!

**Pull request closed without merging**
